"""TouchPoint module taxonomy for docs/touchpoint/ splits."""

from __future__ import annotations

# Module folder name → human label
MODULES: dict[str, str] = {
    "activation": "Font Sync / Activation",
    "library": "Library / Font Lists",
    "projects": "Projects",
    "favourites": "Favourites",
    "imported_fonts": "Imported Fonts / BYOF / Production",
    "documents": "Documents / Upload / Contracts",
    "tags": "Private Tags",
    "teams_orgs": "Teams / Orgs / Users / SSO",
    "notifications": "Notifications / Preferences",
    "sharing": "Sharing / Assets / Pins",
    "other": "Other / Misc GraphQL",
    "ingress": "Ingress APIs (Desktop / Plugin)",
    "cron": "Cron / Scheduler Jobs",
}

# operation → module (GraphQL mutations + known ops)
OP_MODULE: dict[str, str] = {
    # Activation
    "activateFamily": "activation",
    "deactivateFamilies": "activation",
    "activateStyle": "activation",
    "deactivateStyle": "activation",
    "activateVariation": "activation",
    "deactivateVariation": "activation",
    "activateList": "activation",
    "deActivateList": "activation",
    "activateFontProject": "activation",
    "deActivateFontProject": "activation",
    "bulkActivateStyles": "activation",
    "bulkDeactivateStyles": "activation",
    "bulkActivateLists": "activation",
    "bulkDeactivateLists": "activation",
    "syncUnSyncVariations": "activation",
    "fontAutoActivated": "activation",
    "fontAutoDeactivated": "activation",
    "fontTempActivated": "activation",
    # Favourites
    "addFavoriteFamilies": "favourites",
    "addFavoriteStyles": "favourites",
    "removeFavoriteFamilies": "favourites",
    "removeFavoriteStyles": "favourites",
    "addFavoritePair": "favourites",
    "removeFavoritePair": "favourites",
    "bulkAddPairsToFavorite": "favourites",
    "bulkRemovePairsFromFavorite": "favourites",
    "bulkAddStylesToFavourites": "favourites",
    "bulkRemoveStylesFromFavourites": "favourites",
    # Library / lists
    "createAsset": "library",
    "updateAsset": "library",
    "updateAssets": "library",
    "deleteAssets": "library",
    "addFontListFamilies": "library",
    "addFontListStyles": "library",
    "removeFontListFamilies": "library",
    "removeFontListStyles": "library",
    "bulkAddStylesToList": "library",
    "bulkRemoveStylesFromList": "library",
    "bulkCopyAssets": "library",
    "bulkMoveAssets": "library",
    "keepInProduction": "library",
    "createAssetAttachmentUpload": "library",
    "deleteAssetAttachment": "library",
    "finalizeAssetAttachments": "library",
    "downloadAssetAttachmentSignedUrl": "library",
    # Projects
    "createProject": "projects",
    "createWebProject": "projects",
    "editWebProject": "projects",
    "publishProject": "projects",
    "duplicateProject": "projects",
    "deleteProject": "projects",
    "addFontProjectFamilies": "projects",
    "addFontProjectStyles": "projects",
    "removeFontProjectFamilies": "projects",
    "removeFontProjectStyles": "projects",
    "updateFontProjectStyles": "projects",
    "addStylesToWebProject": "projects",
    "removeStylesFromWebProject": "projects",
    "downloadWebProject": "projects",
    # Imported / production / BYOF
    "createBYOFBatchAndCheckDuplicates": "imported_fonts",
    "uploadImportedFonts": "imported_fonts",
    "deleteImportedFonts": "imported_fonts",
    "markProductionFonts": "imported_fonts",
    "bulkUnmarkProductionFont": "imported_fonts",
    "bulkMarkAsProductionFontsRequest": "imported_fonts",
    "updateProductionFont": "imported_fonts",
    "submitIntentForProduction": "imported_fonts",
    "denyIntentForProduction": "imported_fonts",
    "updateFontsForReview": "imported_fonts",
    "createContract": "imported_fonts",
    "parseAndCreateContract": "imported_fonts",
    "updateContract": "imported_fonts",
    "deleteContracts": "imported_fonts",
    "linkContractToStyles": "imported_fonts",
    "unlinkStyleFromContract": "imported_fonts",
    "linkDocumentsToContract": "imported_fonts",
    "unlinkDocumentsFromContract": "imported_fonts",
    "importFontTemplate": "imported_fonts",
    "exportUnassignedImportedFontsTemplate": "imported_fonts",
    # Documents / upload
    "createUploadSession": "documents",
    "updateSessionFiles": "documents",
    "markSessionFileUploaded": "documents",
    "completeUploadSession": "documents",
    "processUploadSessionFonts": "documents",
    "linkDocumentToProject": "documents",
    "unlinkDocumentFromProject": "documents",
    "saveDocumentMetadata": "documents",
    "addStyleComment": "documents",
    "updateStyleComment": "documents",
    "deleteStyleComment": "documents",
    "addStyleDocument": "documents",
    "deleteStyleDocument": "documents",
    "createStyleDocumentsUploadUrl": "documents",
    "createCompanyLogoUploadUrl": "documents",
    "markCompanyLogoUploadSuccess": "documents",
    "deleteCompanyLogo": "documents",
    # Tags
    "createPrivateTags": "tags",
    "updatePrivateTag": "tags",
    "deletePrivateTags": "tags",
    "deleteAllPrivateTags": "tags",
    "bulkTagStyles": "tags",
    "bulkUntagStyles": "tags",
    "updatePrivateTagAssociations": "tags",
    # Teams / orgs
    "createCustomer": "teams_orgs",
    "updateCustomer": "teams_orgs",
    "updateCustomerSettings": "teams_orgs",
    "createTeam": "teams_orgs",
    "updateTeam": "teams_orgs",
    "deleteTeams": "teams_orgs",
    "createRole": "teams_orgs",
    "updateRole": "teams_orgs",
    "deleteRoles": "teams_orgs",
    "createUserInvitations": "teams_orgs",
    "updateUserInvitations": "teams_orgs",
    "updateProfile": "teams_orgs",
    "bulkUpdateProfiles": "teams_orgs",
    "deleteProfiles": "teams_orgs",
    "createServiceAccount": "teams_orgs",
    "updateServiceAccount": "teams_orgs",
    "deleteServiceAccount": "teams_orgs",
    "suspendServiceAccount": "teams_orgs",
    "regenerateToken": "teams_orgs",
    "revokeToken": "teams_orgs",
    "createSsoMapping": "teams_orgs",
    "updateSsoMapping": "teams_orgs",
    "deleteSsoMappings": "teams_orgs",
    "reorderSsoMappings": "teams_orgs",
    "updateCompanySsoStatus": "teams_orgs",
    "resetPassword": "teams_orgs",
    "setLanguagePreference": "teams_orgs",
    "markOnboardingCompleted": "teams_orgs",
    "requestFontAccess": "teams_orgs",
    "approveFontAccess": "teams_orgs",
    "rejectFontAccess": "teams_orgs",
    # Notifications
    "bulkNotificationAction": "notifications",
    "dismissNotification": "notifications",
    "markNotificationRead": "notifications",
    "markAllNotificationsRead": "notifications",
    "updatePreference": "notifications",
    "updateSubToggle": "notifications",
    "bulkUpdatePreferences": "notifications",
    "resetPreferences": "notifications",
    "applyUnsubscribe": "notifications",
    "globalEmailOptOut": "notifications",
    # Sharing
    "updateAssetSharing": "sharing",
    "updateAssetsSharingInfo": "sharing",
    "sharingInfoForAssets": "sharing",
    "pinAsset": "sharing",
    "unpinAsset": "sharing",
    # Other
    "cancelBatch": "other",
    "publishAddOn": "other",
    "submitFontUsageReport": "other",
    "fontSimilarViewed": "other",
}


def module_for(operation: str, *, kind: str = "graphql") -> str:
    if kind == "ingress":
        return "ingress"
    if kind == "cron":
        return "cron"
    return OP_MODULE.get(operation, "other")
