"""Persist the latest comparison result per operation (survives server restarts)."""

from __future__ import annotations

import json
import os
import re
import threading
from pathlib import Path
from typing import Any

_lock = threading.Lock()


def _active_target() -> str:
    raw = (os.getenv("AUDIT_TARGET") or "qa").strip().lower()
    return raw if raw in {"pp", "qa", "uat", "everest"} else "qa"


def _store_path(project_root: Path, target: str | None = None) -> Path:
    """Per-environment store so PP/QA Results never mix."""
    t = (target or _active_target()).strip().lower()
    if t not in {"pp", "qa", "uat", "everest"}:
        t = "qa"
    path = project_root / "reports" / f"comparison-latest-{t}.json"
    return path


def _legacy_store_path(project_root: Path) -> Path:
    return project_root / "reports" / "comparison-latest.json"


def store_audit_target(project_root: Path | None = None, target: str | None = None) -> str:
    return (target or _active_target()).strip().lower() or "qa"


def _load_for_target(project_root: Path, target: str | None = None) -> dict[str, Any]:
    t = store_audit_target(project_root, target)
    path = _store_path(project_root, t)
    data = _load(path)
    # Migrate legacy shared file into pp store on first read.
    if not data and t == "pp":
        legacy = _load(_legacy_store_path(project_root))
        if legacy:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(
                json.dumps(legacy, indent=2, ensure_ascii=False, default=str) + "\n",
                encoding="utf-8",
            )
            return legacy
    return data


def _load(path: Path) -> dict[str, Any]:
    if not path.is_file():
        return {}
    try:
        data = json.loads(path.read_text(encoding="utf-8"))
        return data if isinstance(data, dict) else {}
    except Exception:
        return {}


_GQL_SOURCE_API = "GraphQL curl / event trigger"
_GQL_NOTE_LIVE = "GraphQL mutation response (live replay from captured input)"
_GQL_NOTE_META = "GraphQL mutation response (subject.metadata.result)"


def _clean_legacy_raw_envelope_rows(rows: list[dict[str, Any]]) -> tuple[list[dict[str, Any]], bool]:
    """Relabel rows that still point at the old raw-envelope source of truth."""
    out: list[dict[str, Any]] = []
    changed = False
    for r in rows:
        fp = str(r.get("field_path") or "")
        sys = str(r.get("source_system") or "")
        api = str(r.get("source_api") or "")
        notes = str(r.get("notes") or "")
        legacy = (
            sys == "Raw"
            or "raw event" in notes.lower()
            or "published envelope" in notes.lower()
            or "published envelope" in api.lower()
        )
        if legacy and (
            fp.startswith("source.")
            or fp
            in {
                "xCorrelationId",
                "eventId",
                "eventVersion",
                "occurredAt",
                "routingKey",
            }
        ):
            r = {
                **r,
                "source_system": "Trigger",
                "source_api": _GQL_SOURCE_API,
                "notes": _GQL_NOTE_LIVE if "live replay" in notes.lower() else _GQL_NOTE_META
                if "metadata.result" in notes.lower()
                else _GQL_NOTE_LIVE,
            }
            changed = True
        out.append(r)
    return out, changed


def _clean_scope_rows(rows: list[dict[str, Any]]) -> tuple[list[dict[str, Any]], bool]:
    """Reconcile stored enrichment-scope rows with current validator behaviour.

    Legacy runs stored two misleading SKIPs that the resolver-contract validator
    no longer emits:
      • ``enrichmentScope`` "Operation not in manifest" → dropped (nothing to source).
      • ``enrichmentScope.gap`` produce≠require → now PASS (generated by resolver).
    Returns the cleaned rows and whether anything changed.
    """
    out: list[dict[str, Any]] = []
    changed = False
    for r in rows:
        fp = str(r.get("field_path") or "")
        status = str(r.get("match_status") or "")
        if fp == "enrichmentScope" and status == "SKIP":
            changed = True
            continue  # drop legacy "not in manifest" skip
        if fp == "enrichmentScope.gap" and status != "PASS":
            r = {
                **r,
                "match_status": "PASS",
                "notes": (
                    "Enrichment snapshot generated by audit resolver "
                    "(informational, nothing external to source)"
                ),
            }
            changed = True
        out.append(r)
    return out, changed


_TEAMMATE_EXCEL_NOTE = re.compile(
    r"^Imported from teammate Excel export\.?$",
    re.I,
)


def _clean_import_provenance_notes(
    rows: list[dict[str, Any]],
) -> tuple[list[dict[str, Any]], bool]:
    """Drop noisy 'Imported from teammate Excel export' notes from stored rows."""
    out: list[dict[str, Any]] = []
    changed = False
    for r in rows:
        notes = str(r.get("notes") or "").strip()
        if notes and _TEAMMATE_EXCEL_NOTE.match(notes):
            r = {**r, "notes": ""}
            changed = True
        out.append(r)
    return out, changed


def _clean_benign_client_ua_rows(
    rows: list[dict[str, Any]],
) -> tuple[list[dict[str, Any]], bool]:
    """PASS HeadlessChrome / browser-version UA noise; keep exact values + note."""
    try:
        from audit_validator.source_validation.value_match import (
            CLIENT_UA_NOISE_NOTE,
            is_client_ua_field,
            user_agents_equivalent,
        )
    except Exception:
        return rows, False

    out: list[dict[str, Any]] = []
    changed = False
    for r in rows:
        fp = str(r.get("field_path") or "")
        status = str(r.get("match_status") or "")
        # Excel imports often stored version-only UA diffs as SKIP, not FAIL.
        if status in {"FAIL", "SKIP"} and is_client_ua_field(fp):
            enr = r.get("value_in_enriched")
            src = r.get("value_in_source")
            if str(enr or "").strip() and str(src or "").strip() and user_agents_equivalent(
                src, enr
            ):
                r = {
                    **r,
                    "match_status": "PASS",
                    "notes": CLIENT_UA_NOISE_NOTE,
                }
                changed = True
        out.append(r)
    return out, changed


def _clean_app_ui_be_defaults(
    rows: list[dict[str, Any]],
) -> tuple[list[dict[str, Any]], bool]:
    """PASS false positives: BE mtconnect-api / 1.0.0 vs app UI mtconnect-ui / 1.0.0.0.

    Also strip leftover noisy notes from earlier workarounds.
    """
    out: list[dict[str, Any]] = []
    changed = False
    for r in rows:
        fp = str(r.get("field_path") or "")
        status = str(r.get("match_status") or "")
        notes = str(r.get("notes") or "")
        # Drop noisy BE-workaround wording from prior runs.
        if "BE mtconnect-api" in notes or "BE default ignored" in notes or (
            "Desktop / UI audit ingress" in notes and "ignored" in notes
        ):
            r = {
                **r,
                "notes": "Audit ingress body",
                "source_api": "Audit ingress body",
            }
            changed = True
            notes = r["notes"]
        if status not in {"FAIL", "SKIP"}:
            out.append(r)
            continue
        src = str(r.get("value_in_source") or "").strip()
        enr = str(r.get("value_in_enriched") or "").strip()
        if fp == "source.service" and enr == "mtconnect-ui" and src in {
            "mtconnect-api",
            "",
        }:
            r = {
                **r,
                "value_in_source": "mtconnect-ui",
                "match_status": "PASS",
                "notes": "Audit ingress body",
                "source_api": "Audit ingress body",
            }
            changed = True
        elif fp == "source.platformVersion" and enr == "1.0.0.0" and src in {
            "1.0.0",
            "",
        }:
            r = {
                **r,
                "value_in_source": "1.0.0.0",
                "match_status": "PASS",
                "notes": "Audit ingress body",
                "source_api": "Audit ingress body",
            }
            changed = True
        out.append(r)
    return out, changed


def _summary_for_rows(op_rows: list[dict[str, Any]]) -> dict[str, int]:
    return {
        "passed": sum(1 for r in op_rows if r.get("match_status") == "PASS"),
        "failed": sum(1 for r in op_rows if r.get("match_status") == "FAIL"),
        "skipped": sum(1 for r in op_rows if r.get("match_status") == "SKIP"),
        "na": sum(1 for r in op_rows if r.get("match_status") == "N/A"),
    }


def save_operation_result(
    project_root: Path,
    operation: str,
    *,
    rows: list[dict[str, Any]],
    job_id: str,
    job_kind: str,
    compared_at: str,
    summary: dict[str, Any] | None = None,
    target: str | None = None,
) -> None:
    """Overwrite the stored latest comparison for one operation."""
    op_rows = [r for r in rows if r.get("operation") == operation]
    if not op_rows:
        return
    save_batch_results(
        project_root,
        operation_rows={operation: op_rows},
        job_id=job_id,
        job_kind=job_kind,
        compared_at=compared_at,
        summaries={operation: summary} if summary else None,
        target=target,
    )


def save_batch_results(
    project_root: Path,
    *,
    rows: list[dict[str, Any]] | None = None,
    operation_rows: dict[str, list[dict[str, Any]]] | None = None,
    job_id: str,
    job_kind: str,
    compared_at: str,
    summaries: dict[str, dict[str, Any] | None] | None = None,
    target: str | None = None,
) -> None:
    """Write many operations in one read/write of comparison-latest-{target}.json.

    Passing ``rows`` (flat list) or ``operation_rows`` (already grouped) is fine.
    Avoids the old O(n²) rewrite that reloaded a multi‑MB file per operation.
    """
    grouped: dict[str, list[dict[str, Any]]] = dict(operation_rows or {})
    if rows:
        for r in rows:
            op = str(r.get("operation") or "")
            if not op:
                continue
            grouped.setdefault(op, []).append(r)
    if not grouped:
        return

    audit_target = store_audit_target(project_root, target)
    path = _store_path(project_root, audit_target)
    path.parent.mkdir(parents=True, exist_ok=True)
    with _lock:
        data = _load_for_target(project_root, audit_target)
        if not data and audit_target == "pp":
            data = _load(_legacy_store_path(project_root))
        for op, op_rows in grouped.items():
            if not op_rows:
                continue
            canon = _normalize_result_operation(op)
            cleaned, _ = _clean_import_provenance_notes(op_rows)
            cleaned, _ = _clean_benign_client_ua_rows(cleaned)
            cleaned, _ = _clean_app_ui_be_defaults(cleaned)
            for r in cleaned:
                if isinstance(r, dict):
                    r["operation"] = _normalize_result_operation(
                        str(r.get("operation") or canon)
                    )
            summ = (summaries or {}).get(op) or (summaries or {}).get(canon)
            data[canon] = {
                "operation": canon,
                "compared_at": compared_at,
                "job_id": job_id,
                "job_kind": job_kind,
                "summary": summ or _summary_for_rows(cleaned),
                "rows": cleaned,
            }
        data, _ = _dedupe_channel_variants(data)
        if len(data) >= 20:
            _backup_store(path)
        path.write_text(
            json.dumps(data, indent=2, ensure_ascii=False, default=str) + "\n",
            encoding="utf-8",
        )


def reconcile_scope_rows(project_root: Path) -> dict[str, int]:
    """One-time cleanup: rewrite stored results dropping/upgrading legacy scope SKIPs.

    Returns counts of operations touched and rows changed.
    """
    path = _store_path(project_root)
    with _lock:
        data = _load(path)
        ops_touched = 0
        for op, item in data.items():
            rows = item.get("rows") or []
            cleaned, changed_scope = _clean_scope_rows(rows)
            cleaned, changed_raw = _clean_legacy_raw_envelope_rows(cleaned)
            cleaned, changed_notes = _clean_import_provenance_notes(cleaned)
            cleaned, changed_ua = _clean_benign_client_ua_rows(cleaned)
            cleaned, changed_app = _clean_app_ui_be_defaults(cleaned)
            if changed_scope or changed_raw or changed_notes or changed_ua or changed_app:
                ops_touched += 1
                item["rows"] = cleaned
                item["summary"] = _summary_for_rows(cleaned)
        if ops_touched:
            path.write_text(
                json.dumps(data, indent=2, ensure_ascii=False, default=str) + "\n",
                encoding="utf-8",
            )
    return {"operations_touched": ops_touched}


def _normalize_result_operation(op: str) -> str:
    """Strip legacy ``(UI)`` channel suffix — UI is the default, unlabeled."""
    name = str(op or "").strip()
    if name.endswith("(UI)"):
        return name[: -len("(UI)")]
    if name.endswith("(ui)"):
        return name[: -len("(ui)")]
    return name


def _dedupe_channel_variants(data: dict[str, Any]) -> tuple[dict[str, Any], bool]:
    """Drop redundant ``op(UI)`` / bare-``op(BE)`` when the canonical key exists.

    - UI is unlabeled → ``activateList(list)(UI)`` collapses into ``activateList(list)``.
    - Ingress ``op(BE)`` with no inner touchpoint collapses into bare ``op``.
    - Touchpoint backend labels like ``activateFamily(global)(BE)`` are kept.
    """
    import re

    changed = False
    # 1) Rename/merge *(UI) → bare
    ui_only = re.compile(r"^(.+)\(UI\)$", re.IGNORECASE)
    ui_keys = [op for op in list(data.keys()) if ui_only.match(str(op))]
    for op in ui_keys:
        m = ui_only.match(str(op))
        if not m:
            continue
        bare = m.group(1)
        item = data.pop(op, None)
        if item is None:
            continue
        changed = True
        # Rewrite row operation labels under the bare name
        rows = item.get("rows") or []
        for r in rows:
            if isinstance(r, dict):
                r["operation"] = bare
        item["operation"] = bare
        if bare not in data:
            data[bare] = item
            continue
        # Prefer the newer / higher-pass block
        existing = data[bare]
        def _score(block: dict[str, Any]) -> tuple:
            summ = block.get("summary") or {}
            return (
                str(block.get("compared_at") or ""),
                int(summ.get("pass") or summ.get("PASS") or 0),
                len(block.get("rows") or []),
            )
        if _score(item) > _score(existing):
            data[bare] = item

    # 2) Drop bare-op(BE) when a non-BE variant exists, or for desktop ingress ops
    #    (font*/app*/plugin*) — UI/APP is the source of truth; no parallel BE row.
    be_only = re.compile(r"^([^(]+)\(BE\)$")
    desktop_be_prefixes = (
        "font",
        "app",
        "plugin",
    )
    to_drop: list[str] = []
    keys = [str(k) for k in data.keys()]
    for op in keys:
        m = be_only.match(op)
        if not m:
            continue
        bare = m.group(1)
        bare_l = bare.lower()
        has_non_be = any(
            k != op
            and (k == bare or k.startswith(f"{bare}("))
            and not k.endswith("(BE)")
            and "(BE)" not in k
            for k in keys
        )
        is_desktop_ingress = bare_l.startswith(desktop_be_prefixes)
        if has_non_be or is_desktop_ingress or bare in data:
            to_drop.append(op)
    for op in to_drop:
        data.pop(op, None)
        changed = True
    return data, changed


def list_latest(project_root: Path, *, target: str | None = None) -> dict[str, Any]:
    """All operations with a stored latest comparison, newest first."""
    audit_target = store_audit_target(project_root, target)
    path = _store_path(project_root, audit_target)
    data = _load_for_target(project_root, audit_target)
    data, deduped = _dedupe_channel_variants(data)
    # Clean legacy enrichment-scope SKIP rows on read so the Result view matches
    # current validator behaviour even before the one-time migration runs.
    cleaned_any = False
    for item in data.values():
        rows = item.get("rows") or []
        cleaned, changed_scope = _clean_scope_rows(rows)
        cleaned, changed_raw = _clean_legacy_raw_envelope_rows(cleaned)
        cleaned, changed_notes = _clean_import_provenance_notes(cleaned)
        cleaned, changed_ua = _clean_benign_client_ua_rows(cleaned)
        cleaned, changed_app = _clean_app_ui_be_defaults(cleaned)
        if changed_scope or changed_raw or changed_notes or changed_ua or changed_app:
            cleaned_any = True
            item["rows"] = cleaned
            item["summary"] = _summary_for_rows(cleaned)
    if deduped or cleaned_any:
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(
            json.dumps(data, indent=2, ensure_ascii=False, default=str) + "\n",
            encoding="utf-8",
        )
    for item in data.values():
        item["audit_target"] = audit_target
    # Keep bare base ops and scenario variants side by side (e.g. activateFamily + activateFamily(global)).
    visible_ops = list(data.keys())
    items = [data[op] for op in visible_ops]
    items.sort(key=lambda x: str(x.get("compared_at") or ""), reverse=True)
    merged_rows: list[dict[str, Any]] = []
    for op in sorted(visible_ops):
        merged_rows.extend(data[op].get("rows") or [])
    return {
        "operations": sorted(visible_ops),
        "items": items,
        "rows": merged_rows,
        "count": len(visible_ops),
        "audit_target": audit_target,
        "available_targets": ["qa", "pp", "uat"],
    }


def get_latest_operation(
    project_root: Path, operation: str, *, target: str | None = None
) -> dict[str, Any] | None:
    data = _load_for_target(project_root, target)
    return data.get(operation)


def delete_operation_result(
    project_root: Path, operation: str, *, target: str | None = None
) -> bool:
    """Remove one operation's stored comparison. Returns True if something was deleted."""
    audit_target = store_audit_target(project_root, target)
    path = _store_path(project_root, audit_target)
    with _lock:
        data = _load(path)
        if operation not in data:
            return False
        del data[operation]
        path.write_text(
            json.dumps(data, indent=2, ensure_ascii=False, default=str) + "\n",
            encoding="utf-8",
        )
    return True


def _backup_store(path: Path) -> Path | None:
    """Copy comparison-latest.json before destructive writes."""
    if not path.is_file() or path.stat().st_size < 32:
        return None
    backup = path.with_name(f"{path.stem}.backup.json")
    try:
        backup.write_text(path.read_text(encoding="utf-8"), encoding="utf-8")
        return backup
    except Exception:
        return None


def restore_from_jobs(project_root: Path, *, jobs_path: Path | None = None) -> dict[str, Any]:
    """Merge newest per-operation compare rows from jobs-state (legacy 7-day restore)."""
    from .comparison_restore import restore_from_jobs as _restore

    return _restore(project_root, jobs_path=jobs_path, days=7, update_existing=True)


def clear_all_results(project_root: Path, *, target: str | None = None) -> int:
    """Delete every stored comparison. Returns the number of operations removed."""
    audit_target = store_audit_target(project_root, target)
    path = _store_path(project_root, audit_target)
    with _lock:
        data = _load(path)
        count = len(data)
        if count:
            _backup_store(path)
        path.write_text("{}\n", encoding="utf-8")
    return count


def export_comparison_excel(
    project_root: Path,
    operations: list[str] | None = None,
    *,
    target: str | None = None,
) -> bytes:
    """Build multi-sheet xlsx: one tab per operation with comparison rows."""
    from io import BytesIO

    from openpyxl import Workbook

    audit_target = store_audit_target(project_root, target)
    data = _load_for_target(project_root, audit_target)
    ops = [o for o in (operations or []) if o and o in data]
    if not ops:
        ops = sorted(data.keys())
    headers = [
        "Title",
        "Operation",
        "Enriched JSON path",
        "Enriched",
        "Source",
        "Source value",
        "Status",
    ]
    wb = Workbook()
    wb.remove(wb.active)
    for op in ops:
        item = data.get(op) or {}
        rows = item.get("rows") or []
        title = op[:31].replace("/", "-").replace("\\", "-").replace("*", "").replace("?", "")
        if not title:
            title = "Sheet"
        ws = wb.create_sheet(title=title)
        ws.append(headers)
        for row in rows:
            fp = str(row.get("field_path") or "")
            ws.append(
                [
                    row.get("field") or fp.rsplit(".", 1)[-1],
                    op,
                    f"$.{fp}" if fp else "",
                    row.get("value_in_enriched") or "",
                    row.get("source_system") or "",
                    row.get("value_in_source") or "",
                    row.get("match_status") or "",
                ]
            )
    if not wb.sheetnames:
        ws = wb.create_sheet(title="Results")
        ws.append(headers)
    buf = BytesIO()
    wb.save(buf)
    return buf.getvalue()
