"""activateFamily Excel/UI compare: prefer UI trigger, PASS-when-equal, eventId autogen."""

from __future__ import annotations

import json
from pathlib import Path

from audit_validator.simulation.trigger_context import load_trigger_context
from audit_validator.source_validation.comparison_rows import (
    MappingField,
    _graphql_response_value,
    _row,
    build_comparison_rows,
)


def test_load_trigger_prefers_ui_excel_over_seed(tmp_path: Path):
    trig = tmp_path / "payload" / "trigger"
    trig.mkdir(parents=True)
    (trig / "activateFamily(global).json").write_text(
        json.dumps(
            {
                "graphql_input": {"familyIds": ["794981"]},
                "jwt_identity": {"gcid": "ecf57502-seed"},
            }
        ),
        encoding="utf-8",
    )
    (trig / "activateFamily(global)(UI).json").write_text(
        json.dumps(
            {
                "replay_mode": "playwright_script",
                "capture_source": "playwright_script",
                "jwt_from_excel": True,
                "jwt_identity_note": "JWT claims from Excel auth_token",
                "graphql_input": {},
                "graphql_response": {
                    "activateFamily": {
                        "families": {"nodes": [{"id": "910044682"}]},
                    }
                },
                "jwt_identity": {"gcid": "a4175cbf-excel"},
            }
        ),
        encoding="utf-8",
    )
    loaded = load_trigger_context(tmp_path, "activateFamily(global)")
    assert loaded is not None
    assert loaded["jwt_identity"]["gcid"] == "a4175cbf-excel"
    assert loaded["graphql_response"]["activateFamily"]["families"]["nodes"][0]["id"] == (
        "910044682"
    )


def test_family_id_from_activate_family_response_nodes():
    gql = {
        "activateFamily": {
            "errors": [],
            "families": {
                "totalCount": 1,
                "nodes": [{"id": "910044682", "__typename": "InventoryFamily"}],
            },
        }
    }
    assert (
        _graphql_response_value("subject.metadata.input.familyIds[0]", gql, {})
        == "910044682"
    )


def test_validate_n_equal_values_pass():
    spec = MappingField(
        field="eventVersion",
        node="event",
        sub_node="",
        attribute="eventVersion",
        data_mapping="GraphQL",
        notes="GraphQL curl / event trigger",
        validate="N",
        enriched_path="eventVersion",
        source_system="GraphQL",
        source_api="mutation",
        layer="event",
    )
    row = _row("activateFamily", spec, "1", "1", notes="GraphQL curl / event trigger")
    assert row.match_status == "PASS"


def test_event_id_autogenerated_pass():
    enriched = {
        "eventId": "01KZ3YVF7TP9RVC4SFSWKY4RBM",
        "eventVersion": "1",
        "source": {"operation": "activateFamily", "operationIndex": 0, "platformVersion": "1.0.0"},
        "actor": {"globalCustomerId": "a4175cbf-1419-4a30-aa21-12109bf942f6"},
        "subject": {
            "metadata": {"input": {"familyIds": ["910044682"]}},
            "enrichedSnapshot": {"fontDetails": []},
        },
    }
    live = {
        "trigger": {
            "replay_mode": "playwright_script",
            "jwt_from_excel": True,
            "jwt_identity_note": "JWT claims from Excel auth_token",
            "eventVersion": "1",
            "graphql_input": {},
            "graphql_response": {
                "activateFamily": {"families": {"nodes": [{"id": "910044682"}]}}
            },
            "jwt_identity": {"gcid": "a4175cbf-1419-4a30-aa21-12109bf942f6"},
            "request": {
                "operationIndex": 0,
                "platformVersion": "1.0.0",
                "userAgent": "Chrome/109",
            },
            "source": {
                "operationIndex": 0,
                "platformVersion": "1.0.0",
                "actorUserAgent": "Chrome/109",
            },
        },
        "jwt_identity": {"gcid": "a4175cbf-1419-4a30-aa21-12109bf942f6"},
        "jwt_from_excel": True,
        "graphql_response": {
            "activateFamily": {"families": {"nodes": [{"id": "910044682"}]}}
        },
    }
    rows = build_comparison_rows("activateFamily(global)", enriched, live=live)
    by_path = {r.field_path: r for r in rows}
    assert by_path["eventId"].match_status == "PASS"
    assert "pipeline" in (by_path["eventId"].notes or "").lower() or "accepted" in (
        by_path["eventId"].notes or ""
    ).lower()

    fam = next(
        (r for r in rows if "familyIds" in r.field_path),
        None,
    )
    assert fam is not None
    assert fam.value_in_source == "910044682"
    assert fam.value_in_enriched == "910044682"
    assert fam.match_status == "PASS"

    gcid = next((r for r in rows if r.field_path.endswith("globalCustomerId")), None)
    if gcid:
        assert gcid.value_in_source == "a4175cbf-1419-4a30-aa21-12109bf942f6"
        assert gcid.match_status == "PASS"
